# template for settings relevant to the paSampleComposite browserTrack type

# uncomment this section to include standard settings from widgets/browserTrack/settings.yml
# see: https://github.com/wilsontelab/genomex-mdi-tools
include:
    - height

# uncomment this section to specify settings that are common to multiple tracks in an app or suite
# shared:
#     - ../shared_settings.yml # interpreted relative to the track's own settings.yml file

# uncomment this section to specify track-specific settings, using the same format as for settingsServer
# see: https://midataint.github.io/mdi-apps-framework/docs/settings/yaml-declarations.html
settings:
    TSS_Frags:
        Transcription_State:
            type:   selectInput
            choices:
                - active
                - inactive
            value: active
# uncomment this section to specify track-specific settings
# presets:
#     Preset_Name:
#         Family:
#             Option: value
