# action:
#     find positioned nucleosomes independently of TSSs (but score them based on proximity to TSSs)
#     logic is described in the Rust ab_initio crate called by this script
# input:
#     insert bgz files generated by atac/tss/footprint.R
# outputs:
#     ab_initio.rds for use in the app

#=====================================================================================
# script initialization
#-------------------------------------------------------------------------------------
message("initializing")
suppressPackageStartupMessages(suppressWarnings({
    library(data.table)
    library(parallel)
}))
#-------------------------------------------------------------------------------------
# load, parse and save environment variables
env <- as.list(Sys.getenv())
rUtilDir <- file.path(env$MODULES_DIR, 'utilities', 'R')
source(file.path(rUtilDir, 'workflow.R'))
checkEnvVars(list(
    string = c(
        'PRIMARY_GENOME',
        'PRIMARY_GENOME_FASTA',
        'GENOME',
        'GENOME_METADATA_PREFIX',
        'ACTION_DIR',
        'DATA_FILE_PREFIX',
        'HISTONE_STAGE',
        'PROTAMINE_STAGE',
        'STAGE_TYPES',
        'AB_INITIO_STAGES',
        'TASK_DIR',
        'MDI_DIR'
    ),
    integer = c(
        'N_CPU'
    )
))
#-------------------------------------------------------------------------------------
# source R scripts
rUtilDir <- file.path(env$MODULES_DIR, 'score')
sourceScripts(rUtilDir, c('score_functions'))
#-------------------------------------------------------------------------------------
# set some options
options(scipen = 999) # prevent 1+e6 in printed, which leads to read.table error when integer expected
options(warn = 2) 
#=====================================================================================

#=====================================================================================
# find positioned nucleosomes ab initio
#-------------------------------------------------------------------------------------
message("parsing stages")
stages <- strsplit(env$AB_INITIO_STAGES, ',')[[1]]

message("parsing stage types")
stageTypes <- unpackStageTypes(env)
reverseStageTypes <- {
    reversed <- list()
    for (stageType in names(stageTypes)) {
        for (stage in stageTypes[[stageType]]) {
            reversed[[stage]] <- stageType
        }
    }
    reversed
}
nStageTypes <- length(stageTypes)

message("finding stage insert files")
stageInsertFiles <- sapply(stages, function(stage) {
    stageType <- reverseStageTypes[[stage]]
    if(is.null(stageType)) stageType <- 'NA'
    bgzFilePrefix <- paste(stageType, stage, sep = '.')
    bgzFileName <- paste(bgzFilePrefix, 'bed.bgz', sep = '.')
    insertFile <- file.path(env$TASK_DIR, 'inserts_bgz', bgzFileName)
    if(!file.exists(insertFile)) stop(paste("missing insert file:", insertFile))
    insertFile
}, simplify = TRUE, USE.NAMES = TRUE)

message("loading chromosome metadata")
message(env$PRIMARY_GENOME_FASTA)
chroms <- fread(paste0(env$PRIMARY_GENOME_FASTA, ".fai"))[, 1:2]
setnames(chroms, c('chrom', 'length'))
chroms <- chroms[!grepl('_', chrom) & !grepl('chrM', chrom) & !grepl('chrEBV', chrom)]

message("finding positioned nucleosomes by chromosome")
scoreAbInitio <- file.path(env$MDI_DIR, 'suites/definitive/protamine-tools/pipelines/atac/tss/crates/target/debug/ab_initio')
ab_initio <- do.call(rbind, lapply(which(chroms$chrom == "chr8"), function(chromI) {
# ab_initio <- do.call(rbind, lapply(which(chroms$chrom %in% c("chr1","chr8","chr9")), function(chromI) {
# ab_initio <- do.call(rbind, lapply(1:nrow(chroms), function(chromI) {
    message(paste0("  ", chroms[chromI, chrom], " = ", chroms[chromI, length], " bp"))
    ai <- fread(cmd = paste(
        scoreAbInitio,
        chroms[chromI, chrom],
        chroms[chromI, length],
        paste(stages, collapse = ','),
        paste(stageInsertFiles, collapse = ',')
    ))
    setnames(ai, c(
        'chrom', 'start0', 'end1', 
        'index_stage', 
        'nuc_starts0', 'merge_types', 'dinuc_scores',
        'index_nfr_score', 'index_nuc_score',
        paste(stages, "score", sep = '_'),
        paste(stages, "count", sep = '_')
    ))
    ai
}))
setkey(ab_initio, chrom, start0, end1)

message()
message("saving data for app")
saveRDS(
    ab_initio, 
    file = paste(env$DATA_FILE_PREFIX, "ab_initio.rds", sep = '.')
)
str(ab_initio)
#=====================================================================================
