# action:
#     find positioned nucleosomes independently of TSSs
#     logic is described in the Rust ab_initio crate called by this script
#     examine and cluster regions for rise-and-fall patterns of RPKM values across stages
# input:
#     insert bgz files generated by atac/tss/footprint.R
# outputs:
#     ab_initio.rds for use in the app

#=====================================================================================
# script initialization
#-------------------------------------------------------------------------------------
message("initializing")
suppressPackageStartupMessages(suppressWarnings({
    library(data.table)
    library(parallel)
    library(uwot)
    library(RcppHNSW) # used by uwot::umap2
    library(matrixStats) # for weighted median
}))
#-------------------------------------------------------------------------------------
# load, parse and save environment variables
env <- as.list(Sys.getenv())
rUtilDir <- file.path(env$MODULES_DIR, 'utilities', 'R')
source(file.path(rUtilDir, 'workflow.R'))
checkEnvVars(list(
    string = c(
        'PRIMARY_GENOME',
        'PRIMARY_GENOME_FASTA',
        'GENOME',
        'GENOME_METADATA_PREFIX',
        'ACTION_DIR',
        'DATA_FILE_PREFIX',
        'HISTONE_STAGE',
        'PROTAMINE_STAGE',
        'STAGE_TYPES',
        'AB_INITIO_STAGES',
        'CLUSTERED_STAGES',
        'TASK_DIR',
        'MDI_DIR'
    ),
    integer = c(
        'N_CPU',
        'MIN_SCORE',
        'N_CLUSTERS',
        'UMAP_N_NEIGHBORS'
    ),
    double = c(
        'MIN_MAX_RPKM',
        'MIN_DELTA_MAX_RATIO'
    )
))
#-------------------------------------------------------------------------------------
# source R scripts
rUtilDir <- file.path(env$MODULES_DIR, 'score')
sourceScripts(rUtilDir, c('score_functions'))
#-------------------------------------------------------------------------------------
# set some options
options(scipen = 999) # prevent 1+e6 in printed, which leads to read.table error when integer expected
options(warn = 2) 
#=====================================================================================

#=====================================================================================
# find positioned nucleosomes ab initio
#-------------------------------------------------------------------------------------
message("parsing stages")
stages <- strsplit(env$AB_INITIO_STAGES, ',')[[1]]
nStages <- length(stages)
stage_score_cols  <- paste(stages, "score",  sep = '_')
stage_count_cols  <- paste(stages, "count",  sep = '_')
stage_rpkm_cols   <- paste(stages, "rpkm",   sep = '_')
stage_scaled_cols <- paste(stages, "scaled", sep = '_')
clusteredStages <- strsplit(env$CLUSTERED_STAGES, ',')[[1]]
clustered_rpkm_cols   <- paste(clusteredStages, "rpkm",   sep = '_')
clustered_scaled_cols <- paste(clusteredStages, "scaled", sep = '_')
indexedStages <- c('overlap_group', clusteredStages)

message("parsing stage types")
stageTypes <- unpackStageTypes(env)
reverseStageTypes <- {
    reversed <- list()
    for (stageType in names(stageTypes)) {
        for (stage in stageTypes[[stageType]]) {
            reversed[[stage]] <- stageType
        }
    }
    reversed
}
nStageTypes <- length(stageTypes)

message("finding stage insert files")
stageInsertFiles <- sapply(stages, function(stage) {
    stageType <- reverseStageTypes[[stage]]
    if(is.null(stageType)) stageType <- 'NA'
    bgzFilePrefix <- paste(stageType, stage, sep = '.')
    bgzFileName <- paste(bgzFilePrefix, 'bed.bgz', sep = '.')
    insertFile <- file.path(env$TASK_DIR, 'inserts_bgz', bgzFileName)
    if(!file.exists(insertFile)) stop(paste("missing insert file:", insertFile))
    insertFile
}, simplify = TRUE, USE.NAMES = TRUE)

message("loading chromosome metadata")
message(env$PRIMARY_GENOME_FASTA)
chroms <- fread(paste0(env$PRIMARY_GENOME_FASTA, ".fai"))[, 1:2]
setnames(chroms, c('chrom', 'length'))
chroms <- chroms[!grepl('_', chrom) & !grepl('chrM', chrom) & !grepl('chrEBV', chrom)]

message("loading nInserts by stage")
fp_stage <- readRDS(paste(env$DATA_FILE_PREFIX, "footprint.rds", sep = '.'))$footprint$stage
nInserts <- sapply(stages, function(stage) fp_stage[[stage]]$nInserts, simplify = FALSE, USE.NAMES = TRUE)
rm(fp_stage)

message("finding positioned dinucleosomes by chromosome")
scoreAbInitio <- file.path(env$MDI_DIR, 'suites/definitive/protamine-tools/resources/ab_initio') # compiled Rust binary
# regions <- do.call(rbind, lapply(which(chroms$chrom == "chr8"), function(chromI) {
# regions <- do.call(rbind, lapply(which(chroms$chrom %in% c("chr1","chr8","chr9")), function(chromI) {
regions <- do.call(rbind, lapply(1:nrow(chroms), function(chromI) {
    message(paste0("  ", chroms[chromI, chrom], " = ", chroms[chromI, length], " bp"))
    regions <- fread(cmd = paste(
        scoreAbInitio,
        chroms[chromI, chrom],
        chroms[chromI, length],
        paste(stages, collapse = ','),
        paste(stageInsertFiles, collapse = ','),
        paste(unlist(nInserts), collapse = ','),
        env$MIN_SCORE
    ))
    setnames(regions, c(
        'chrom', 'start0', 'end1', 
        'index_stage', 
        'nuc_starts0', 'merge_types', 'dinuc_scores',
        'index_nfr_score', 'index_nuc_score',
        stage_score_cols,
        stage_count_cols
    ))
    regions
}))
setkey(regions, chrom, start0, end1)

message("converting counts to RPKM") # column-wise normalization; feature dimension reduction not required since so few stages
k <- regions[, (end1 - start0) / 1e3]
for(stage in stages){ 
    stage_count_col  <- paste(stage, "count",  sep = '_')
    stage_rpkm_col   <- paste(stage, "rpkm",   sep = '_')
    r <- regions[[stage_count_col]] / 2 # correct by two since inserts were mostly counted twice, once per end
    m <- nInserts[[stage]] / 1e6
    regions[[stage_rpkm_col]] <- r / k / m
}
rm(r, k, m)

message("scaling regions as log2 fold-change from the mean of all stages") # row-wise normalization
scaled <- do.call(rbind, mclapply(1:nrow(regions), function(i) {
    rpkm <- unlist(regions[i, ..stage_rpkm_cols])
    mean_rpkm <- mean(rpkm, na.rm = TRUE)
    data.table(t(log2(rpkm / mean_rpkm))) # can yield -Inf if stage rpkm == 0 in a region; must be handled downstream; mean_rpkm cannot be 0
}, mc.cores = env$N_CPU))
setnames(scaled, stage_scaled_cols)
regions <- cbind(regions, scaled)
rm(scaled)

message("filtering regions based on max and delta RPKM")
regions$min_RPKM <- apply(regions[, ..stage_rpkm_cols], 1, min, na.rm = TRUE)
regions$max_RPKM <- apply(regions[, ..stage_rpkm_cols], 1, max, na.rm = TRUE)
regions$delta_RPKM <- (regions$max_RPKM - regions$min_RPKM)
nRegionIn <- nrow(regions)
regions[, passed_rpkm_filters := 
    max_RPKM >= env$MIN_MAX_RPKM & 
    delta_RPKM / max_RPKM >= env$MIN_DELTA_MAX_RATIO
]
nRegionsOut <- regions[, sum(passed_rpkm_filters, na.rm = TRUE)]
message(paste(
    "  filtered", nRegionIn, "regions to", nRegionsOut, 
    "regions with max RPKM >=", env$MIN_MAX_RPKM, 
    "and delta / max RPKM >=", env$MIN_DELTA_MAX_RATIO
))  

message("profiling region signals across stages") # profiling is done for all regions, not just those passing filters
regions$stage_mean <- apply(regions[, ..stage_rpkm_cols], 1, function(rpkm) {
    weightedMedian(1:nStages, rpkm, interpolate = TRUE, na.rm = TRUE) # numeric value at the centroid of the stage RPKM weights
})
regions$mean_stage <- as.integer(round(regions$stage_mean)) # the single stage closest to the weighted median
regions$max_stage  <- apply(regions[, ..stage_rpkm_cols], 1, which.max) # the single stage at the profile peak

message("calculating region RPKM quantiles by index stage and filters") # quantile determined once with, once without, RPKM filters
getQuantiles <- function(stage_means){
    as.integer(cut(
        stage_means, 
        breaks = quantile(stage_means, probs = seq(0, 1, 1 / env$N_CLUSTERS), na.rm = TRUE), 
        include.lowest = TRUE
    ))
}
regions[, indexI := 1:.N, by = .(index_stage)]
regions[,                            quantile_unfiltered := getQuantiles(stage_mean), by = .(index_stage)]
regions[passed_rpkm_filters == TRUE, quantile_filtered   := getQuantiles(stage_mean), by = .(index_stage)]

message("solving region umaps by index stage") # umap applied after applying RPKM filters; unpassed regions will be NA
# unscaled considers RPKM magnitude in clustering, scaled focuses on relative differences
# euclidean metric matches kmeans below, correlation focuses purely on rise and fall patterns
umap_types <- c(
    "unscaled_euclidean",
    "scaled_euclidean",
    "scaled_correlation"
)
index_stages <- regions[ # includes "overlap_group", but some stages may not have had any regions passing filters
    passed_rpkm_filters == TRUE & 
    index_stage %in% indexedStages, 
    unique(index_stage)
]
for(umap_type in umap_types) { # use for loops since umap is parallelized
    message(paste0("  ", umap_type))
    umap1_col <- paste0(umap_type, "_umap1")
    umap2_col <- paste0(umap_type, "_umap2")
    regions[[umap1_col]] <- NA
    regions[[umap2_col]] <- NA
    umap_type_parts <- strsplit(umap_type, '_')[[1]]
    stage_cols <- if(umap_type_parts[1] == "scaled") clustered_scaled_cols else clustered_rpkm_cols
    for(index_stage_ in index_stages) {
        message(paste0("    ", index_stage_))
        indexI <- regions[, passed_rpkm_filters & index_stage == index_stage_]
        umap <- umap2(
            regions[indexI, ..stage_cols],
            n_neighbors = env$UMAP_N_NEIGHBORS, 
            metric      = umap_type_parts[2],
            nn_method   = "hnsw",
            n_threads   = env$N_CPU - 1
        )
        regions[[umap1_col]][indexI] <- umap[, 1]
        regions[[umap2_col]][indexI] <- umap[, 2]
    }
}

message(paste("clustering regions by index stage, k =", env$N_CLUSTERS)) # kmeans applied after applying RPKM filters; unpassed regions will be NA
scalings <- c(
    "unscaled", # kmeans is always euclidean
    "scaled"
) 
nstart <- 10
iter.max <- 500
for (scaling in scalings){
    message(paste0("  ", scaling))
    kmeans_col <- paste0(scaling, "_cluster")
    regions[[kmeans_col]] <- NA_integer_
    stage_cols <- if(scaling == "scaled") clustered_scaled_cols else clustered_rpkm_cols
    for(index_stage_ in index_stages) {
        message(paste0("    ", index_stage_))
        indexI <- regions[, passed_rpkm_filters & index_stage == index_stage_]
        m <- as.matrix(regions[indexI, ..stage_cols])
        regions[[kmeans_col]][indexI] <- tryCatch(kmeans(
            m,
            centers  = env$N_CLUSTERS,
            nstart   = nstart,
            iter.max = iter.max
        )$cluster, error = function(e) {
            message("      kmeans error: retrying with Lloyd algorithm")
            tryCatch(kmeans(
                m,
                centers   = env$N_CLUSTERS,
                nstart    = nstart,
                iter.max  = iter.max,
                algorithm = "Lloyd"
            )$cluster, error = function(e) {
                message("      kmeans error: returning NA for all regions.")
                NA_integer_
            })
        })
    }
}

# round RPKM values for tidy display in app
for(column in c(
    stage_rpkm_cols, 
    stage_scaled_cols,
    "min_RPKM",
    "max_RPKM",
    "delta_RPKM",
    "stage_mean"
)) {
    regions[[column]] <- round(regions[[column]], 3)
}

message()
message("saving data for app")
obj <- list(
    env = env[c(
        'AB_INITIO_STAGES',
        'MIN_MAX_RPKM',
        'MIN_DELTA_MAX_RATIO',
        'N_CLUSTERS',
        'UMAP_N_NEIGHBORS'
    )],
    stages            = stages,
    clusteredStages   = clusteredStages,
    indexedStages     = indexedStages,
    stageTypes        = stageTypes,
    reverseStageTypes = reverseStageTypes,
    chroms            = chroms,
    nInserts          = nInserts,
    regions           = regions
)
saveRDS(
    obj, 
    file = paste(env$DATA_FILE_PREFIX, "ab_initio.rds", sep = '.')
)
str(obj)
#=====================================================================================
