# action:
#     in parallel over multiple samples:
#         profile ATAC inserts at base-level resolution around active TSSs
# input:
#     sample metadata file
#     genome TSS file generated by `nascent tss`
#     aligned, sorted, and indexed bam files (not necessarily deduplicated, we will dedup)
# outputs:
#     env         = list of environment variables
#     samples     = data.table of sample metadata
#     stageTypes  = list of spermiogenic stage types for each sample, used for aggregation in app
#     reference   = list of reference genome data
#     tss         = data.table of active TSSs
#     tssFrags    = list of data.tables of ATAC inserts around active TSSs

#=====================================================================================
# script initialization
#-------------------------------------------------------------------------------------
message("initializing")
suppressPackageStartupMessages(suppressWarnings({
    library(data.table)
    library(parallel)
}))
#-------------------------------------------------------------------------------------
# load, parse and save environment variables
env <- as.list(Sys.getenv())
rUtilDir <- file.path(env$MODULES_DIR, 'utilities', 'R')
source(file.path(rUtilDir, 'workflow.R'))
checkEnvVars(list(
    string = c(
        'METADATA_FILE',
        'GENOME_INPUT_DIR',
        'GENOME',
        'GENOME_FASTA',
        'ACTION_DIR',
        'DATA_FILE_PREFIX',
        'TSS_BED',
        'ACTIVE_TSS_BED',
        'HISTONE_STAGE',
        'PROTAMINE_STAGE',
        'STAGE_TYPES'
    ),
    integer = c(
        'MIN_MAPQ',
        'MIN_INSERT_SIZE',
        'MAX_INSERT_SIZE',
        'N_CPU'
    )
))
#-------------------------------------------------------------------------------------
# source R scripts
rUtilDir <- file.path(env$MODULES_DIR, 'score')
sourceScripts(rUtilDir, c('score_functions'))
#-------------------------------------------------------------------------------------
# set some options
options(scipen = 999) # prevent 1+e6 in printed, which leads to read.table error when integer expected
options(warn = 2) 
#=====================================================================================

#=====================================================================================
# loop through all BAM files to determine their coverage in each genome bin
#-------------------------------------------------------------------------------------

message("loading sample metadata")
samples <- fread(env$METADATA_FILE)
# samples <- samples[filename_prefix %in% c("24290X11", "24290X9")]
nSamples <- nrow(samples)

message("parsing spermiogenic stage types")
stageTypes <- unpackStageTypes(env)

message("parsing reference")
reference <- list(
    input_dir   = env$GENOME_INPUT_DIR,
    genome      = env$GENOME,
    fai_file    = paste0(env$GENOME_FASTA, '.fai'),
    tss_file    = if(env$TSS_BED == 'NA') env$ACTIVE_TSS_BED else env$TSS_BED
)

message("loading active TSSs")
tss <- {
    tss <- fread(reference$tss_file) # already restricted by nascent/tss to autosomes and chrX/Y
    reference$chroms <- tss[, unique(chrom)]
    reference$n_tss <- nrow(tss)
    tss
}

message("collecting sample inserts around active TSSs")
getChromInserts <- paste('bash', file.path(env$ACTION_DIR, 'get_chrom_inserts.sh'))
tssFrags <- mclapply(1:nSamples, function(sampleI) {
# tssFrags <- lapply(1:nSamples, function(sampleI) {
    sample <- samples[sampleI]
    message(paste('   ', sample$filename_prefix, '=', sample$sample_name))
    bamFile <- file.path(reference$input_dir, paste0(sample$filename_prefix, '.*.bam'))
    do.call(rbind, lapply(reference$chroms, function(chrom) { # all bins values over all ordered chroms
        fread(cmd = paste(getChromInserts, bamFile, chrom, reference$tss_file)) # one value per TSS-region base on chrom
    }))
}, mc.cores = env$N_CPU)
# })
names(tssFrags) <- samples$sample_name

message()
message("saving TSS inserts for app")
obj <- list(
    env         = env[c("MAX_INSERT_SIZE","GENOME","HISTONE_STAGE","PROTAMINE_STAGE")],
    samples     = samples,
    stageTypes  = stageTypes,
    reference   = reference,
    tss         = tss,
    tssFrags    = tssFrags
)
saveRDS(
    obj, 
    file = paste(env$DATA_FILE_PREFIX, "tssFrags.rds", sep = '.')
)
str(obj)
#=====================================================================================
