# template for settings relevant to the paGenomeGc browserTrack type

# uncomment this section to include standard settings from widgets/browserTrack/settings.yml
# see: https://github.com/wilsontelab/genomex-mdi-tools
# include:
#     - height, etc.

# uncomment this section to specify settings that are common to multiple tracks in an app or suite
# shared:
#     - ../shared_settings.yml # interpreted relative to the track's own settings.yml file

# uncomment this section to specify track-specific settings, using the same format as for settingsServer
# see: https://midataint.github.io/mdi-apps-framework/docs/settings/yaml-declarations.html
settings:
    Bin_Display:
        Height_Pixels:
            type:   numericInput
            value:  10
            min:    6
            max:    25
            step:   1
        Max_Fold_Center:
            type:   numericInput
            value:  1.4
            min:    1
            max:    2
            step:   0.1
    # Bin_Filters:
    #     Min_Percent_GC:
    #         type:   numericInput
    #         value:  0.25
    #         min:    0
    #         max:    1
    #         step:   0.025
    #     Max_Percent_GC:
    #         type:   numericInput
    #         value:  0.75
    #         min:    0
    #         max:    1
    #         step:   0.025
# uncomment this section to specify track-specific settings
# presets:
#     Preset_Name:
#         Family:
#             Option: value
