# template for settings relevant to the paSampleComposite browserTrack type

# uncomment this section to include standard settings from widgets/browserTrack/settings.yml
# see: https://github.com/wilsontelab/genomex-mdi-tools
include:
    - height

# uncomment this section to specify settings that are common to multiple tracks in an app or suite
# shared:
#     - ../shared_settings.yml # interpreted relative to the track's own settings.yml file

# uncomment this section to specify track-specific settings, using the same format as for settingsServer
# see: https://midataint.github.io/mdi-apps-framework/docs/settings/yaml-declarations.html
settings:
    Footprint:
        Aggregate_By:
            type:   selectInput
            choices:
                - sample
                - stage
                - stage_type
            value: stage
        Plot_Inserts_As:
            type:   selectInput
            choices:
                - v_plot
                - insert_spans
                - endpoint_counts
            value: v_plot
        Max_Width_Bases:
            type:   numericInput
            value:  100000
        Max_Insert_Size:
            type:   numericInput
            value:  450
        Endpoint_Counts_As:
            type:   selectInput
            choices:
                - counts
                - weights
            value: counts
        Endpoint_Normalize_To:
            type:   selectInput
            choices:
                - window
                - genome
            value: genome
        Endpoint_Max_Quantile:
            type:   numericInput
            value:  0.99
        Endpoint_Line_Width:
            type:   numericInput
            value:  1.5
        V_Plot_Point_Size:
            type:   numericInput
            value:  0.75
        Color_Inserts_By:
            type:   selectInput
            choices:
                - blue
                - black
                - stage
            value: blue
        Insert_Line_Width:
            type:   numericInput
            value:  1.25
        Insert_Color_Alpha:
            type:   numericInput
            value:  0.5
    Data_Path:
        Inserts_Bgz_Dir:
            type:   textInput
            value:  ""
# uncomment this section to specify track-specific settings
# presets:
#     Preset_Name:
#         Family:
#             Option: value
