# template for settings relevant to the paSampleComposite browserTrack type

# uncomment this section to include standard settings from widgets/browserTrack/settings.yml
# see: https://github.com/wilsontelab/genomex-mdi-tools
# include:
#     - height, etc.

# uncomment this section to specify settings that are common to multiple tracks in an app or suite
# shared:
#     - ../shared_settings.yml # interpreted relative to the track's own settings.yml file

# uncomment this section to specify track-specific settings, using the same format as for settingsServer
# see: https://midataint.github.io/mdi-apps-framework/docs/settings/yaml-declarations.html
settings:
    Bin_Display:
        Bin_Center_Type:
            type:   selectInput
            value:  rpba
            choices:
                - rpba
                - subnucleosomal_fraction
                - gc_adj_z_score
        Sample_Height_Pixels:
            type:   numericInput
            value:  10
            min:    6
            max:    25
            step:   1
        Max_Axis_Value:
            type:   numericInput
            value:  10
            min:    1
            max:    25
            step:   1
# uncomment this section to specify track-specific settings
# presets:
#     Preset_Name:
#         Family:
#             Option: value
