#----------------------------------------------------------------------
# R package dependencies common to many apps
#----------------------------------------------------------------------
packages:
  R:  
    - imager
    - signal
    - matrixStats
  Bioconductor: 
    - AnnotationHub
    - CTCF
