# action:
#     import two nascent RNA bigwig files, one for each primary genome strand
#     as needed, liftover the input nascent RNA-seq data to PRIMARY_GENOME
#     use the nascent RNA-seq data to create a genome-wide TSS map that:
#         is _stranded_ (in contrast to nascent/bin)
#         carries relative gene transcription levels as RPKM over the 1st 1kb of the gene
#         carries the fold increase in stranded transcription level of the 1st 1kb of the gene relative to the 1kb upstream (i.e., the promoter)
#            together, these values help identify true TSSs of significantly transcribed genes
# input:
#     two nascent RNA bigwig files for PRIMARY_GENOME
#     composite genome gene map as a BED file, as created by `genome download` and `genome composite`
#     optional liftover chain file from bigwig genome to PRIMARY_GENOME
# where, we generally assumme Pro-seq data are:
#     from: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE228452 
#     and thus were: "generated by summing counts per nucleotide across replicates"
#     i.e., each strand file has one entry for every covered base, with its count of matching read 3' ends
# output:
#     TSS map as a composite-genome-wide BED file where 
#         chrom     = chromosomes, named the same as COMPOSITE_GENOME
#         start     = TSS1 - 1000bp
#         end       = TSS1 + 1000bp
#         name      = gene name from genome tss table
#         score     = gene_size = gene size in bp
#         strand    = strand of the gene
#         gene_start_rpkm = RPKM over the 1st 1kb of the gene
#         tss_fold_increase = fold increase in transcription level of the 1st 1kb of the gene relative to the 1kb upstream (i.e., the promoter)

#=====================================================================================
# script initialization
#-------------------------------------------------------------------------------------
message("initializing")
suppressPackageStartupMessages(suppressWarnings({
    library(rtracklayer)
    library(data.table)
    library(parallel)
}))
#-------------------------------------------------------------------------------------
# load, parse and save environment variables
env <- as.list(Sys.getenv())
rUtilDir <- file.path(env$MODULES_DIR, 'utilities', 'R')
source(file.path(rUtilDir, 'workflow.R'))
checkEnvVars(list(
    string = c(
        'PRIMARY_GENOME',
        'BIGWIG_FILE_FORWARD',
        'BIGWIG_FILE_REVERSE',
        'LIFTOVER_CHAIN',
        'GENES_BED',
        'PLOT_PREFIX',
        'PA_TSS_BED'
    ),
    integer = c(
        'N_CPU'
    )
))
#-------------------------------------------------------------------------------------
# set some options
options(scipen = 999) # prevent 1+e6 in printed, which leads to read.table error when integer expected
options(warn = 2)
#-------------------------------------------------------------------------------------
TSS_FLANK_LEN    <- 1000L
TSS_FLANK_OFFSET <- TSS_FLANK_LEN - 1L
TSS_FLANK_LEN_KB <- TSS_FLANK_LEN / 1000L
MIN_TSS_RPKM     <- 0.5
MIN_TSS_FOLD_INC <- 10
#=====================================================================================

#=====================================================================================
# do the work
#-------------------------------------------------------------------------------------
message("importing (and lifting over) bigwig files")
nascent <- do.call(rbind, mclapply(c(env$BIGWIG_FILE_FORWARD, env$BIGWIG_FILE_REVERSE), function(bw_file) {
# nascent <- do.call(rbind, lapply(c(env$BIGWIG_FILE_FORWARD, env$BIGWIG_FILE_REVERSE), function(bw_file) {

    message(paste(" ", "importing", bw_file))
    bw_data <- import(bw_file, format = "bigWig") # a GRanges object
    if(env$LIFTOVER_CHAIN != "NA") {
        message(paste(" ", "lifting with ", env$LIFTOVER_CHAIN))
        chain <- import.chain(env$LIFTOVER_CHAIN)
        bw_data <- unlist(liftOver(bw_data, chain))
    }

    # convert to data.table
    # width is always 1
    # chrom names in bigwig files expected to match PRIMARY_GENOME with chrom names like chr1, chrX
    dt <- as.data.table(bw_data) 
    rm(bw_data)
    strandX <- if(bw_file == env$BIGWIG_FILE_FORWARD) "+" else "-" 
    dt[, .(chrom = as.character(seqnames), start1 = start, end1 = start, count = score, strand = strandX)]
}, mc.cores = env$N_CPU))
# }))

message("calculating total counts")
millionCounts <- sum(nascent$count) / 1e6
message(paste(" ", "total counts (M):", millionCounts))

message(paste0("loading canonical-chromosome genes >= ", TSS_FLANK_LEN, "bp"))
# GENES_BED expected to match COMPOSITE_GENOME, with chrom names like chr1-mm39, chr2L-dm6
genes <- fread(env$GENES_BED)
names(genes) <- c('chrom', 'start0', 'end1', 'name', 'score', 'strand')
allowed_chroms <- paste0("chr", c(as.character(1:22), "X", "Y"), "-", env$PRIMARY_GENOME) # only canonical mammalian chromosomes
genes <- genes[
    chrom %in% allowed_chroms & 
    end1 - start0 >= TSS_FLANK_LEN
]
message(paste(" ", "total usable genes:", nrow(genes)))

message("parsing 1kb upstream and downstream of gene TSSs")
tss <- genes[, {
    .(
        start1 = if(strand == '+') c(
            start0 - TSS_FLANK_OFFSET,  # upstream/promoter (-1)
            start0 + 1L                 # downstream/gene_body (1)
        ) else c(
            end1 + 1L,                  # upstream/promoter
            end1 - TSS_FLANK_OFFSET     # downstream/gene_body
        ),
        end1 = if(strand == '+') c(
            start0, 
            start0 + TSS_FLANK_LEN
        ) else c(
            end1 + TSS_FLANK_LEN,
            end1
        ),
        tss1 = if(strand == '+') start0 + 1L else end1,
        gene_size = end1 - start0,
        side = c(-1, 1)
    )
}, keyby = .(chrom, name, strand)]

message("adjusting chrom names to match composite genome")
nascent[, chrom := paste0(chrom, "-", env$PRIMARY_GENOME)]

message("calculating cpm of TSS upstream and downstream regions")
tss <- do.call(rbind, mclapply(unique(tss$chrom), function(chrom_) {
# tss <- do.call(rbind, lapply(unique(tss$chrom), function(chrom_) {
    message(paste(" ", "processing", chrom_))
    do.call(rbind, lapply(c("+", "-"), function(strand_) {
        nascent_ <- nascent[chrom == chrom_ & strand == strand_]
        tss_     <- tss[    chrom == chrom_ & strand == strand_]
        setkey(tss_, start1, end1)
        foverlaps(
            nascent_[, .(start1, end1, count)],
            tss_, 
            type = "any",
            mult = "all",
            nomatch = NULL,
            which = FALSE
        )[, 
            .(
                count = sum(count, na.rm = TRUE)
            ),
            keyby = .(
                chrom, 
                name, 
                strand, 
                tss1, 
                gene_size, 
                side
            )
        ][, 
            {
                if(.N == 1) count <- if(side == -1) c(count, 0) else c(0, count)
                .(
                    upstream_rpkm     = count[1] / TSS_FLANK_LEN_KB / millionCounts,
                    gene_start_rpkm   = count[2] / TSS_FLANK_LEN_KB / millionCounts,
                    tss_fold_increase = count[2] / count[1],
                    tss_increase      = (count[2] - count[1]) / TSS_FLANK_LEN_KB / millionCounts
                )
            },
            keyby = .(
                chrom, 
                name, 
                strand, 
                tss1, 
                gene_size
            )
        ]
    }))
}, mc.cores = env$N_CPU))
# }))

# plot to help optimize active TSS filters
message("plotting TSS parameters")
pngFile <- paste(env$PLOT_PREFIX, "nascent.tss.png", sep = '.')
png(pngFile, width = 3, height = 3, units = "in", res = 600, pointsize = 8, type = "cairo")
plot(
    tss$gene_start_rpkm, 
    tss$tss_increase, 
    xlab = "gene_start_rpkm", 
    ylab = "tss_increase", 
    main = "nascent TSS parameters",
    typ = "p",
    pch = ".",
    col = ifelse(
        tss$gene_start_rpkm   >= MIN_TSS_RPKM &
        tss$tss_fold_increase >= MIN_TSS_FOLD_INC,
        rgb(0, 0, 1, 0.1),
        rgb(0, 0, 0, 0.1)
    ),
    xlim = c(0, 25),
    ylim = c(-10, 25)
)
dev.off()

message("writing TSS output file")
tss <- tss[, .(
    chrom, 
    start = tss1 - TSS_FLANK_LEN, 
    end   = tss1 + TSS_FLANK_LEN, 
    name, 
    gene_size, 
    strand, 
    upstream_rpkm,
    gene_start_rpkm, 
    tss_fold_increase
)][
    order(chrom, start, end)
]
fwrite(
    tss,
    file = env$PA_TSS_BED,
    quote = FALSE,
    row.names = FALSE,
    col.names = TRUE,
    sep = '\t'
)
message()
str(tss)
