---
pipeline:
    name: atac
    description: "prepare protamine ATAC-seq data for analysis in the interactive app"
    # version: v0.0.1
# suiteVersions:
#     suiteName: v0.0.0
actions: 
    _global:   
        environment: protamine-tools
        condaFamilies:
            - base
            - protaminer
            - r-4.4
    align:
        order: 1
        optionFamilies:
            - samples
            - genome
            - alignment
            - quality
        resources:
            required:
                total-ram: 32G
            recommended: 
                n-cpu: 16
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 30:00:00
        description: "parse and align ATAC-seq reads to the composite genome using Bowtie2"
    sites:
        order: 2
        optionFamilies:
            - samples
            - composite
            - genome
            - quality
            - bin
        resources:
            required:
                total-ram: 8G
            recommended: 
                n-cpu: 14
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 12:00:00
        description: "count discontiguous nonamers at the cleavage site of observed ATAC-seq inserts"
    collate:
        order: 3
        optionFamilies:
            - samples
            - composite
            - genome
            - quality
            - bin
            - stage
            - score
        resources:
            required:
                total-ram: 8G
            recommended: 
                n-cpu: 14
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 12:00:00
        description: "collate read data across all samples into high resolution bins with various scores"
    tss:
        order: 4
        optionFamilies:
            - composite
            - genome
            - annotation
            - stage
            - tss
        resources:
            required:
                total-ram: 8G
            recommended: 
                n-cpu: 4
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 2:00:00
        description: "map ATAC fragments around (in)active TSSs at base-level resolution"
package:
    sites: # the pipeline action after which a data package should assembled
        uploadType: protamine-atac-sites # a signal to the Stage 2 framework regarding the package contents
        files:
            samples-metadata-file:
                type: csv
                file: $METADATA_FILE
            n-inserts-by-stage:
                type: tsv
                file: $DATA_FILE_PREFIX.n_inserts_by_stage.txt
            tn5-kmers-file:
                type: csv
                file: $TN5_KMERS_FILE
            primary-sites-observed:
                type: rds
                file: $DATA_FILE_PREFIX.primary.tn5_site_counts_obs.rds
            spike-in-sites-observed:
                type: rds
                file: $DATA_FILE_PREFIX.spike_in.tn5_site_counts_obs.rds
            primary-sites-expected:
                type: rds
                file: $GENOME_METADATA_PREFIX.primary.tn5_site_counts_exp.rds
            spike-in-sites-expected:
                type: rds
                file: $GENOME_METADATA_PREFIX.spike_in.tn5_site_counts_exp.rds
    collate: # the pipeline action after which a data package should assembled
        uploadType: protamine-atac-collate # a signal to the Stage 2 framework regarding the package contents
        files:
            collate:
                type: rds
                file: $DATA_FILE_PREFIX.collate.rds
            # scores:
            #     type: rds
            #     file: $DATA_FILE_PREFIX.scores.rds
    tss:
        uploadType: protamine-atac-tss # a signal to the Stage 2 framework regarding the package contents
        files:
            tssFrags:
                type: rds
                file: $DATA_FILE_PREFIX.tssFrags.rds
container:
    supported: false
    registry:  ghcr.io  # domain name of your OCI-compatible, oras-accessible, container registry [ghcr.io]
    owner:     xxxxxxxx # the name of the owner, e.g., user or organization, at 'registry'
    installer: apt-get  # the installer program used by the container OS, typically apt-get or yum [apt-get]
