---
pipeline:
    name: atac
    description: "prepare spermatid ATAC-seq data for analysis in the interactive app"
    # version: v0.0.1
# suiteVersions:
#     suiteName: v0.0.0
actions: 
    _global:   
        environment: protamine-tools
        condaFamilies:
            - base
            - protaminer
            - r-4.4
    align:
        order: 1
        optionFamilies:
            - samples
            - genome
            - alignment
            - quality
        resources:
            required:
                total-ram: 32G
            recommended: 
                n-cpu: 16
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 30:00:00
        description: "parse and align ATAC-seq reads to the composite genome using Bowtie2"
    sites:
        order: 2
        optionFamilies:
            - samples
            - composite
            - genome
            - quality
            - bin
        resources:
            required:
                total-ram: 8G
            recommended: 
                n-cpu: 14
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 12:00:00
        description: "count discontiguous nonamers at the cleavage site of observed ATAC-seq inserts"
    collate:
        order: 3
        optionFamilies:
            - samples
            - composite
            - genome
            - quality
            - bin
            - stage
            - score
        resources:
            required:
                total-ram: 8G
            recommended: 
                n-cpu: 14
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 12:00:00
        description: "collate read data across all samples into high resolution bins with various scores"
    tss:
        order: 4
        optionFamilies:
            - composite
            - genome
            - annotation
            - stage
            - tss
            - ab_initio
        resources:
            required:
                total-ram: 8G
            recommended: 
                n-cpu: 4
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 4:00:00
        description: "map ATAC fragments around (in)active TSSs at base-level resolution"
    intersect:
        order: 5
        optionFamilies:
            - samples
            - composite
            - genome
            - quality
            - bin
            - stage
            - score
        resources:
            required:
                total-ram: 8G
            recommended: 
                n-cpu: 4
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 4:00:00
        description: "intersect read data with genomic annotations"
    recollate:
        order: 6
        optionFamilies:
            - samples
            - composite
            - genome
            - quality
            - bin
            - stage
            - score
        resources:
            required:
                total-ram: 8G
            recommended: 
                n-cpu: 14
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 12:00:00
        description: "redo the collate action excluding bins that overlap high-accessibility peaks at/near TSSs"
package:
    sites: # the pipeline action after which a data package should assembled
        uploadType: protamine-atac-sites # a signal to the Stage 2 framework regarding the package contents
        files:
            samples-metadata-file:
                type: csv
                file: $METADATA_FILE
            n-inserts-by-stage:
                type: tsv
                file: $DATA_FILE_PREFIX.n_inserts_by_stage.txt
            tn5-kmers-file:
                type: csv
                file: $TN5_KMERS_FILE
            primary-sites-observed:
                type: rds
                file: $DATA_FILE_PREFIX.primary.tn5_site_counts_obs.rds
            spike-in-sites-observed:
                type: rds
                file: $DATA_FILE_PREFIX.spike_in.tn5_site_counts_obs.rds
            primary-sites-expected:
                type: rds
                file: $GENOME_METADATA_PREFIX.primary.tn5_site_counts_exp.rds
            spike-in-sites-expected:
                type: rds
                file: $GENOME_METADATA_PREFIX.spike_in.tn5_site_counts_exp.rds
    collate: # the pipeline action after which a data package should assembled
        uploadType: protamine-atac-collate # a signal to the Stage 2 framework regarding the package contents
        files:
            collate:
                type: rds
                file: $DATA_FILE_PREFIX.collate.rds
            gcBiasModels:
                type: rds
                file: $DATA_FILE_PREFIX.gcBiasModels.rds
            scores: # no longer includes the bin-level score matrices, only score summaries
                type: rds
                file: $DATA_FILE_PREFIX.scores.rds
            cuttag:
                type: rds
                file: $DATA_FILE_PREFIX.cuttag.rds
    tss:
        uploadType: protamine-atac-tss # a signal to the Stage 2 framework regarding the package contents
        files:
            tssFrags:
                type: rds
                file: $DATA_FILE_PREFIX.tssFrags.rds
            footprint:
                type: rds
                file: $DATA_FILE_PREFIX.footprint.rds
            scores: # to support paScoreMap track in tss app
                type: rds
                file: $DATA_FILE_PREFIX.scores.rds
            ab_initio:
                type: rds
                file: $DATA_FILE_PREFIX.ab_initio.rds
            lag_analysis:
                type: rds
                file: $DATA_FILE_PREFIX.lag_analysis.rds
            cuttag:
                type: rds
                file: $DATA_FILE_PREFIX.cuttag.rds
        extraPushFiles: # files pushed to remote server in addition to the data package but not included in the package
            - $TASK_DIR/scores
            - $TASK_DIR/inserts_bgz
            - $TASK_DIR/nfr_bgz
    recollate: # the pipeline action after which a data package should assembled
        uploadType: protamine-atac-recollate # a signal to the Stage 2 framework regarding the package contents
        files:
            collate:
                type: rds
                file: $DATA_FILE_PREFIX.recollate.rds
            gcBiasModels:
                type: rds
                file: $DATA_FILE_PREFIX.recollated.gcBiasModels.rds
            scores: # no longer includes the bin-level score matrices, only score summaries
                type: rds
                file: $DATA_FILE_PREFIX.recollated.scores.rds
            tssFrags:
                type: rds
                file: $DATA_FILE_PREFIX.tssFrags.rds
            footprint:
                type: rds
                file: $DATA_FILE_PREFIX.footprint.rds
            ab_initio:
                type: rds
                file: $DATA_FILE_PREFIX.ab_initio.rds
            # lag_analysis:
            #     type: rds
            #     file: $DATA_FILE_PREFIX.lag_analysis.rds
        # extraPushFiles: # files pushed to remote server in addition to the data package but not included in the package
        #     - $TASK_DIR/scores
        #     - $TASK_DIR/inserts_bgz
        #     - $TASK_DIR/nfr_bgz
container:
    supported: false
    registry:  ghcr.io  # domain name of your OCI-compatible, oras-accessible, container registry [ghcr.io]
    owner:     xxxxxxxx # the name of the owner, e.g., user or organization, at 'registry'
    installer: apt-get  # the installer program used by the container OS, typically apt-get or yum [apt-get]
