---
pipeline:
    name: genome
    description: "download and prepare genome files for binned analysis"
    # version: v0.0.1
# suiteVersions:
#     suiteName: v0.0.0
actions: 
    _global:   
        environment: protamine-tools
        condaFamilies:
            - base
            - protaminer
            - r-4.4
    download:
        order: 1
        optionFamilies:
            - download-genome
            - annotation
        resources:
            required:
                total-ram: 8G
            recommended: 
                n-cpu: 1
                ram-per-cpu: 8G
        job-manager:
            recommended:
                time-limit: 1:00:00
        description: "download genomes and required support files"
    composite:
        order: 2
        optionFamilies:
            - composite
            - genome
        resources:
            required:
                total-ram: 8G
            recommended: 
                n-cpu: 1
                ram-per-cpu: 8G
        job-manager:
            recommended:
                time-limit: 1:00:00
        description: "combine a primary and spike-in genome into composite genome and metadata files"
    mappability:
        order: 3
        optionFamilies:
            - genome
            - bin
        resources:
            required:
                total-ram: 64G
            recommended: 
                n-cpu: 16
                ram-per-cpu: 4G
        job-manager:
            recommended:
                time-limit: 24:00:00
        description: "create mappability files for the composite genome at various insert sizes"
    bin:
        order: 4
        optionFamilies:
            - genome
            - bin
        resources:
            required:
                total-ram: 8G
            recommended: 
                n-cpu: 4
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 2:00:00
        description: "create bins on composite genome nuclear chroms with inclusion flag, GC, and mappability"
container:
    supported: false
    registry:  ghcr.io  # domain name of your OCI-compatible, oras-accessible, container registry [ghcr.io]
    owner:     xxxxxxxx # the name of the owner, e.g., user or organization, at 'registry'
    installer: apt-get  # the installer program used by the container OS, typically apt-get or yum [apt-get]
